# Site metadata

title: Emad Masroor

description: Academic website of Emad Masroor

url: "https://emadmasroor.github.io"
baseurl: ""

# Contact

author: Emad Masroor
email: emad@vt.edu
github_username: emadmasroor
orcid: 0000-0002-8770-1429
rss: feed.xml
# Build settings

theme: minima

feed:
  tags: true
